exposure: 1.63999999
gamma: 1.34000003
sky_filename: assets/night.hdr
camera:
  position: [8.84460449, 4.82340908, -5.85941267]
  direction: [-0.612012982, -0.351408154, 0.708266497]
objects:
  - type: sphere
    position: [0, 1, 0]
    radius: 1
    materialIndex: 1
  - type: sphere
    position: [2, 1, 0]
    radius: 1
    materialIndex: 2
  - type: sphere
    position: [4, 1, 0]
    radius: 1
    materialIndex: 3
  - type: sphere
    position: [6, 1, 0]
    radius: 1
    materialIndex: 4
  - type: sphere
    position: [8, 1, 0]
    radius: 1
    materialIndex: 5
  - type: sphere
    position: [1.36000001, 6.42999983, 0]
    radius: 2.20000005
    materialIndex: 6
  - type: sphere
    position: [6.53000021, 5.28999996, 0]
    radius: 0.670000017
    materialIndex: 7
  - type: plane
    normal: [0, 1, 0]
    distance: 0
    materialIndex: 0
  - type: triangle
    a: [-0.49000001, 2.61999989, 0.589999974]
    b: [-1.69000006, -0.699999988, 0.970000029]
    c: [-0.730000019, 0.430000007, 2.52999997]
    materialIndex: 0
materials:
  - albedo: [0.800000012, 0.800000012, 0.800000012]
    emissivity: [0, 0, 0]
    roughness: 0
    texture_coordinates_multiplier: 1.38999999
    texture_id: 0
    metallic_texture_id: 2
    normal_texture_id: 1
  - albedo: [0.689999998, 0.639999986, 0]
    emissivity: [0, 0, 0]
    roughness: 0
    texture_coordinates_multiplier: 1
    texture_id: 3
    metallic_texture_id: 5
    normal_texture_id: 4
  - albedo: [0.800000012, 0.800000012, 0.300000012]
    emissivity: [0, 0, 0]
    roughness: 0.150000006
    texture_coordinates_multiplier: 1
    texture_id: 6
    metallic_texture_id: 8
    normal_texture_id: 7
  - albedo: [0, 0.800000012, 0.800000012]
    emissivity: [0, 0, 0]
    roughness: 0.300000012
    texture_coordinates_multiplier: 1
    texture_id: 9
    metallic_texture_id: 11
    normal_texture_id: 10
  - albedo: [0.800000012, 0, 0.800000012]
    emissivity: [0, 0, 0]
    roughness: 0.899999976
    texture_coordinates_multiplier: 1
    texture_id: 12
    metallic_texture_id: 14
    normal_texture_id: 13
  - albedo: [0, 0, 0]
    emissivity: [0, 0, 0]
    roughness: 0
    texture_coordinates_multiplier: 1
    texture_id: 15
    metallic_texture_id: 17
    normal_texture_id: 16
  - albedo: [0, 0, 0]
    emissivity: [30.1000004, 43.8400002, 0]
    roughness: 1
    texture_coordinates_multiplier: 1
    texture_id: -1
    metallic_texture_id: -1
    normal_texture_id: -1
  - albedo: [0, 0, 0]
    emissivity: [55.8400002, 4.82999992, 0]
    roughness: 1
    texture_coordinates_multiplier: 1
    texture_id: -1
    metallic_texture_id: -1
    normal_texture_id: -1
textures:
  - assets/grass/albedo.png
  - assets/grass/normal.png
  - assets/grass/metallic.png
  - assets/stone/albedo.png
  - assets/stone/normal.png
  - assets/stone/metallic.psd
  - assets/granite/albedo.png
  - assets/granite/normal.png
  - assets/granite/metallic.psd
  - assets/ice/albedo.png
  - assets/ice/normal.png
  - assets/ice/metallic.psd
  - assets/gold/albedo.png
  - assets/gold/normal.png
  - assets/gold/metallic.png
  - assets/tile/albedo.png
  - assets/tile/normal.png
  - assets/tile/metallic.psd