exposure: 3.11999989
gamma: 1.03999996
blur_radius: 0
sky_filename: assets/sky.hdr
camera:
  position: [4.65383005, 1.44152522, -5.77163172]
  direction: [3.40025872e-06, -0.0466598831, 0.998712122]
objects:
  - type: sphere
    name: Sphere brick
    position: [ 0, 1, 0 ]
    radius: 1
    materialIndex: 1
  - type: sphere
    name: Sphere tiles
    position: [ 2, 1, 0 ]
    radius: 1
    materialIndex: 2
  - type: sphere
    name: Sphere ice
    position: [ 4, 1, 0 ]
    radius: 1
    materialIndex: 3
  - type: sphere
    name: Sphere gold
    position: [ 6, 1, 0 ]
    radius: 1
    materialIndex: 4
  - type: sphere
    name: Sphere tiles
    position: [ 8, 1, 0 ]
    radius: 1
    materialIndex: 5
  - type: plane
    name: Plane
    normal: [ 0, 1, 0 ]
    distance: 0
    materialIndex: 0
materials:
  - name: Plane material
    albedo: [ 0.800000012, 0.800000012, 0.800000012 ]
    emissivity: [ 0, 0, 0 ]
    roughness: 0
    texture_coordinates_multiplier: 1.38999999
    texture_id: 0
    metallic_texture_id: 2
    normal_texture_id: 1
  - name: Brick
    albedo: [ 0.689999998, 0.639999986, 0 ]
    emissivity: [ 0, 0, 0 ]
    roughness: 0
    texture_coordinates_multiplier: 1
    texture_id: 3
    metallic_texture_id: 5
    normal_texture_id: 4
  - name: Tiles black
    albedo: [ 0.800000012, 0.800000012, 0.300000012 ]
    emissivity: [ 0, 0, 0 ]
    roughness: 0.150000006
    texture_coordinates_multiplier: 1
    texture_id: 6
    metallic_texture_id: 8
    normal_texture_id: 7
  - name: Ice
    albedo: [ 0, 0.800000012, 0.800000012 ]
    emissivity: [ 0, 0, 0 ]
    roughness: 0.300000012
    texture_coordinates_multiplier: 1
    texture_id: 9
    metallic_texture_id: 11
    normal_texture_id: 10
  - name: Gold
    albedo: [ 0.800000012, 0, 0.800000012 ]
    emissivity: [ 0, 0, 0 ]
    roughness: 0.899999976
    texture_coordinates_multiplier: 1
    texture_id: 12
    metallic_texture_id: 14
    normal_texture_id: 13
  - name: Tiles brown
    albedo: [ 0, 0, 0 ]
    emissivity: [ 0, 0, 0 ]
    roughness: 0
    texture_coordinates_multiplier: 1
    texture_id: 15
    metallic_texture_id: 17
    normal_texture_id: 16
textures:
  - assets/grass/albedo.png
  - assets/grass/normal.png
  - assets/grass/metallic.png
  - assets/stone/albedo.png
  - assets/stone/normal.png
  - assets/stone/metallic.psd
  - assets/granite/albedo.png
  - assets/granite/normal.png
  - assets/granite/metallic.psd
  - assets/ice/albedo.png
  - assets/ice/normal.png
  - assets/ice/metallic.psd
  - assets/gold/albedo.png
  - assets/gold/normal.png
  - assets/gold/metallic.png
  - assets/tile/albedo.png
  - assets/tile/normal.png
  - assets/tile/metallic.psd