camera:
  position: [2.98798275, 0.920886874, -4.61193895]
  direction: [0.0327203795, -0.0185958073, 0.99921912]
objects:
  - type: sphere
    position: [0, 1, 0]
    radius: 1
    materialIndex: 1
  - type: sphere
    position: [2, 1, 0]
    radius: 1
    materialIndex: 2
  - type: sphere
    position: [4, 1, 0]
    radius: 1
    materialIndex: 3
  - type: sphere
    position: [6, 1, 0]
    radius: 1
    materialIndex: 4
  - type: plane
    normal: [0, 1, 0]
    distance: 0
    materialIndex: 0
materials:
  - albedo: [0.800000012, 0.800000012, 0.800000012]
    roughness: 1
    texture_coordinates_multiplier: 0.569999993
    texture_id: 0
    metallic_texture_id: 2
    normal_texture_id: 1
  - albedo: [0.689999998, 0.639999986, 0]
    roughness: 0
    texture_coordinates_multiplier: 1
    texture_id: -1
    metallic_texture_id: -1
    normal_texture_id: -1
  - albedo: [0.800000012, 0.800000012, 0.300000012]
    roughness: 0.150000006
    texture_coordinates_multiplier: 1
    texture_id: -1
    metallic_texture_id: -1
    normal_texture_id: -1
  - albedo: [0, 0.800000012, 0.800000012]
    roughness: 0.300000012
    texture_coordinates_multiplier: 1
    texture_id: -1
    metallic_texture_id: -1
    normal_texture_id: -1
  - albedo: [0.800000012, 0, 0.800000012]
    roughness: 0.899999976
    texture_coordinates_multiplier: 1
    texture_id: -1
    metallic_texture_id: -1
    normal_texture_id: -1
textures:
  - assets/stone/albedo.png
  - assets/stone/normal.png
  - assets/stone/metallic.psd