camera:
  position: [3.13852859, 1.41719902, -4.4567318]
  direction: [-0.00429128157, -0.108744189, 0.994008899]
objects:
  - type: sphere
    position: [0, 1, 0]
    radius: 1
    materialIndex: 1
  - type: sphere
    position: [2, 1, 0]
    radius: 1
    materialIndex: 2
  - type: sphere
    position: [4, 1, 0]
    radius: 1
    materialIndex: 3
  - type: sphere
    position: [6, 1, 0]
    radius: 1
    materialIndex: 4
  - type: plane
    normal: [0, 1, 0]
    distance: 0
    materialIndex: 0
materials:
  - albedo: [0.800000012, 0.800000012, 0.800000012]
    roughness: 1
    texture_coordinates_multiplier: 0.400000006
    texture_id: 0
  - albedo: [0.689999998, 0.639999986, 0]
    roughness: 0
    texture_coordinates_multiplier: 1
    texture_id: -1
  - albedo: [0.800000012, 0.800000012, 0.300000012]
    roughness: 0.150000006
    texture_coordinates_multiplier: 1
    texture_id: -1
  - albedo: [0, 0.800000012, 0.800000012]
    roughness: 0.300000012
    texture_coordinates_multiplier: 1
    texture_id: -1
  - albedo: [0.800000012, 0, 0.800000012]
    roughness: 0.899999976
    texture_coordinates_multiplier: 1
    texture_id: -1
textures:
  - assets/stone.png
  - assets/normal.png