#include "version.glsl"
#include "compute.glsl"

uniform sampler2D sky;
uniform sampler2DArray texArray;
uniform isampler2DArray trianglesTexture;
uniform sampler2DArray verticesTexture;
uniform sampler2DArray boundingVolumesTexture;

#include "uniforms.h"

layout (std140, binding = GLOBAL_DATA_BINDING) uniform GlobalDataStruct;
layout (std140, binding = SCENE_BINDING) uniform SceneBufferStruct;

#include "ray_tracing.glsl"

void main()
{
  Ray ray;
  ray.origin = cameraPosition.xyz;
  ray.direction = calculateRayDirection(cameraDirection.xyz, cameraRight.xyz, cameraUp.xyz, texCoord, halfWidth, halfHeight);
  outColor(vec4(castRay(ray), 1.0));
}