#include "version.glsl"
#include "compute.glsl"

uniform sampler2D sky;
uniform sampler2DArray texArray;
uniform isampler2DArray trianglesTexture;

#include "uniforms.h"

layout (std140, binding = GLOBAL_DATA_BINDING) uniform GlobalDataStruct;
layout (std140, binding = SCENE_BINDING) uniform SceneBufferStruct;

#include "ray_tracing.glsl"

void main()
{
  if (useSSAA != 1)
  {
    Ray ray;
    ray.origin = cameraPosition.xyz;
    ray.direction = calculateRayDirection(cameraDirection.xyz, cameraRight.xyz, cameraUp.xyz, texCoord, halfWidth, halfHeight);
    outColor(vec4(castRay(ray), 1.0));
  }
  else
  {
    Ray ray;
    vec2 pixelSize = 1.0 / windowSize.xy;
    vec2 cellSize = pixelSize / SSAAGridSize;
    float x = -cellSize.x * SSAAGridSize / 2.0 + cellSize.x * 0.5 + cellSize.x * (accumulationIndex % SSAAGridSize);
    float y = -cellSize.y * SSAAGridSize / 2.0 + cellSize.y * 0.5 + cellSize.y * floor((accumulationIndex / SSAAGridSize) % SSAAGridSize);
    ray.origin = cameraPosition.xyz;
    ray.direction = calculateRayDirection(cameraDirection.xyz, cameraRight.xyz, cameraUp.xyz, texCoord + vec2(x, y), halfWidth, halfHeight);
    outColor(vec4(castRay(ray), 1.0));
  }
}
