#include "version.glsl"
#include "compute.glsl"

#include "uniforms.h"
layout (std140, binding = GLOBAL_DATA_BINDING) uniform GlobalDataStruct;

#include "utils.glsl"
#include "fxaa.glsl"

uniform sampler2D renderedTexture;
uniform sampler2D bloomTexture;

void main()
{
  if (postProcessing != 1)
  {
    outColor(vec4(texture(renderedTexture, texCoord).xyz, 1.0));
    return;
  }

  vec4 resultColor;
  if (useFXAA == 1)
  {
    resultColor = fxaa(renderedTexture, texCoord, windowSize.xy);
  }
  else
  {
    resultColor = vec4(texture(renderedTexture, texCoord).xyz, 1.0);
  }

  if (renderMode == 1)
  {
    resultColor.rgb += max(gaussian_blur(bloomTexture, windowSize.xy, texCoord, blurSize), vec3(0.0));
  }

  vec3 mapped = vec3(1.0) - exp(-resultColor.rgb * exposure);
  mapped = pow(mapped, vec3(1.0 / gamma));
  resultColor = vec4(mapped, 1.0);
  outColor(resultColor);
}