#include "version.glsl"
#include "compute.glsl"

#include "uniforms.h"
layout (std140, binding = GLOBAL_DATA_BINDING) uniform GlobalDataStruct;

#include "utils.glsl"
#include "fxaa.glsl"

uniform sampler2D u_renderedTexture;
uniform sampler2D u_bloomTexture;

vec3 ACESFilm(vec3 x)
{
  float a = 2.51f;
  float b = 0.03f;
  float c = 2.43f;
  float d = 0.59f;
  float e = 0.14f;
  return clamp((x*(a*x+b))/(x*(c*x+d)+e), 0.0, 1.0);
}

void main()
{
  if (u_postProcessing != 1)
  {
    outColor(vec4(texture(u_renderedTexture, texCoord).xyz, 1.0));
    return;
  }

  vec4 resultColor;
  if (u_useFXAA == 1)
  {
    resultColor = fxaa(u_renderedTexture, texCoord, u_windowSize.xy);
  }
  else
  {
    resultColor = vec4(texture(u_renderedTexture, texCoord).xyz, 1.0);
  }

  if (u_renderMode == 1 && u_blurSize != 0)
  {
    resultColor.rgb += max(gaussian_blur(u_bloomTexture, u_windowSize.xy, texCoord, u_blurSize), vec3(0.0));
  }

  vec3 mapped = vec3(1.0) - exp(-resultColor.rgb * u_exposure);
  mapped = pow(mapped, vec3(1.0 / u_gamma));
  mapped = ACESFilm(mapped);
  resultColor = vec4(mapped, 1.0);
  outColor(resultColor);
}